/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./public/**/*.html"],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0d1117",
        "secondary-container": "#3fb950",
        "secondary": "#79c0ff",
        "surface-container-low": "#161b22",
        "on-background": "#e6edf3",
        "background": "#0d1117",
        "on-surface": "#e6edf3",
        "on-secondary": "#0d1117",
        "primary-container": "#58a6ff",
        "error": "#f7787c",
        "outline-variant": "#30363d",
        "surface-tint": "#79c0ff",
        "primary": "#58a6ff",
        "surface-container-highest": "#282e36",
        "surface-bright": "#30363d",
        "surface-container": "#161b22",
        "on-primary": "#0d1117",
        "surface-container-high": "#21262d",
        "surface-variant": "#30363d",
        "on-surface-variant": "#c9d1d9",
        "on-tertiary": "#0d1117",
        "tertiary": "#8b949e",
        "on-primary-fixed-variant": "#0a3069",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        lg: "24px",
        sm: "8px",
        "margin-mobile": "16px",
        xl: "32px",
        "margin-desktop": "32px",
        xs: "4px",
        base: "4px",
        "2xl": "48px",
        gutter: "20px",
      },
      fontFamily: {
        "label-md": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
